# Generated by Django 5.0.1 on 2024-02-20 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_room_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="create",
            new_name="created",
        ),
    ]
